export const INITIAL_PARTS_DATA = [
  { name: "Filtro de Óleo", brand: "Honda", model: "Universal", year: "2024", color: "Nao se aplica", price: 35.9, photoURL: "https://example.com/moto/filtro_oleo.jpg" },
  { name: "Óleo de Motor", brand: "Yamalube", model: "4T", year: "2024", color: "Nao se aplica", price: 49.9, photoURL: "https://example.com/moto/oleo_motor.jpg" },
  { name: "Vela de Ignição", brand: "NGK", model: "BPR6ES", year: "2024", color: "Nao se aplica", price: 28.5, photoURL: "https://example.com/moto/vela_ngk.jpg" },
  { name: "Bateria 12V", brand: "Moura", model: "MA7-E", year: "2024", color: "Nao se aplica", price: 189.9, photoURL: "https://example.com/moto/bateria_moura.jpg" },
  { name: "Pastilha de Freio", brand: "Cobreq", model: "N-942", year: "2024", color: "Nao se aplica", price: 79.9, photoURL: "https://example.com/moto/pastilha_freio.jpg" },
  { name: "Disco de Freio", brand: "Cobreq", model: "D-123", year: "2024", color: "Nao se aplica", price: 159.9, photoURL: "https://example.com/moto/disco_freio.jpg" },
  { name: "Kit Relação", brand: "DID", model: "520H", year: "2024", color: "Nao se aplica", price: 329.9, photoURL: "https://example.com/moto/kit_relacao.jpg" },
  { name: "Corrente de Comando", brand: "DID", model: "92RH", year: "2024", color: "Nao se aplica", price: 129.9, photoURL: "https://example.com/moto/corrente.jpg" },
  { name: "Coroa", brand: "Riffel", model: "43T", year: "2024", color: "Nao se aplica", price: 89.9, photoURL: "https://example.com/moto/coroa.jpg" },
  { name: "Pinhão", brand: "Riffel", model: "14T", year: "2024", color: "Nao se aplica", price: 49.9, photoURL: "https://example.com/moto/pinhao.jpg" },
  { name: "Amortecedor", brand: "Cofap", model: "M-123", year: "2024", color: "Nao se aplica", price: 249.9, photoURL: "https://example.com/moto/amortecedor.jpg" },
  { name: "Bengala Dianteira", brand: "Cofap", model: "B-456", year: "2024", color: "Nao se aplica", price: 399.9, photoURL: "https://example.com/moto/bengala.jpg" },
  { name: "Retentor de Bengala", brand: "Vedamotors", model: "R-789", year: "2024", color: "Nao se aplica", price: 39.9, photoURL: "https://example.com/moto/retentor_bengala.jpg" },
  { name: "Guidão", brand: "Pro Tork", model: "G-101", year: "2024", color: "Preto", price: 119.9, photoURL: "https://example.com/moto/guidao.jpg" },
  { name: "Manete de Freio", brand: "Pro Tork", model: "M-202", year: "2024", color: "Prata", price: 29.9, photoURL: "https://example.com/moto/manete_freio.jpg" },
  { name: "Manete de Embreagem", brand: "Pro Tork", model: "M-303", year: "2024", color: "Prata", price: 29.9, photoURL: "https://example.com/moto/manete_embreagem.jpg" },
  { name: "Cabo de Embreagem", brand: "Controlflex", model: "C-404", year: "2024", color: "Nao se aplica", price: 49.9, photoURL: "https://example.com/moto/cabo_embreagem.jpg" },
  { name: "Cabo de Acelerador", brand: "Controlflex", model: "C-505", year: "2024", color: "Nao se aplica", price: 44.9, photoURL: "https://example.com/moto/cabo_acelerador.jpg" },
  { name: "Retrovisor", brand: "GVS", model: "R-606", year: "2024", color: "Preto", price: 39.9, photoURL: "https://example.com/moto/retrovisor.jpg" },
  { name: "Pisca (Par)", brand: "Magnetron", model: "P-707", year: "2024", color: "Laranja", price: 59.9, photoURL: "https://example.com/moto/pisca.jpg" },
  { name: "Farol Completo", brand: "Magnetron", model: "F-808", year: "2024", color: "Nao se aplica", price: 189.9, photoURL: "https://example.com/moto/farol.jpg" },
  { name: "Lanterna Traseira", brand: "Magnetron", model: "L-909", year: "2024", color: "Vermelho", price: 79.9, photoURL: "https://example.com/moto/lanterna.jpg" },
  { name: "Regulador Retificador", brand: "Magnetron", model: "R-101", year: "2024", color: "Nao se aplica", price: 129.9, photoURL: "https://example.com/moto/regulador.jpg" },
  { name: "Estator", brand: "Magnetron", model: "E-202", year: "2024", color: "Nao se aplica", price: 249.9, photoURL: "https://example.com/moto/estator.jpg" },
  { name: "Bomba de Combustível", brand: "Bosch", model: "B-303", year: "2024", color: "Nao se aplica", price: 199.9, photoURL: "https://example.com/moto/bomba_combustivel.jpg" },
  { name: "Filtro de Ar", brand: "Tecfil", model: "A-404", year: "2024", color: "Nao se aplica", price: 45.9, photoURL: "https://example.com/moto/filtro_ar.jpg" },
  { name: "Pistão", brand: "Metal Leve", model: "P-505", year: "2024", color: "Nao se aplica", price: 159.9, photoURL: "https://example.com/moto/pistao.jpg" },
  { name: "Anel de Pistão", brand: "Metal Leve", model: "A-606", year: "2024", color: "Nao se aplica", price: 79.9, photoURL: "https://example.com/moto/anel_pistao.jpg" },
  { name: "Junta do Motor", brand: "Sabó", model: "J-707", year: "2024", color: "Nao se aplica", price: 69.9, photoURL: "https://example.com/moto/junta_motor.jpg" },
  { name: "Bomba de Óleo", brand: "Honda", model: "B-808", year: "2024", color: "Nao se aplica", price: 189.9, photoURL: "https://example.com/moto/bomba_oleo.jpg" },
  { name: "Radiador", brand: "Valeo", model: "R-909", year: "2024", color: "Nao se aplica", price: 349.9, photoURL: "https://example.com/moto/radiador.jpg" },
  { name: "Mangueira Radiador", brand: "Gates", model: "M-101", year: "2024", color: "Preto", price: 39.9, photoURL: "https://example.com/moto/mangueira_radiador.jpg" },
  { name: "Ventoinha", brand: "Valeo", model: "V-202", year: "2024", color: "Preto", price: 129.9, photoURL: "https://example.com/moto/ventoinha.jpg" },
  { name: "Pedal de Freio", brand: "Pro Tork", model: "P-303", year: "2024", color: "Prata", price: 59.9, photoURL: "https://example.com/moto/pedal_freio.jpg" },
  { name: "Pedal de Câmbio", brand: "Pro Tork", model: "P-404", year: "2024", color: "Prata", price: 59.9, photoURL: "https://example.com/moto/pedal_cambio.jpg" },
  { name: "Pedaleira", brand: "Pro Tork", model: "P-505", year: "2024", color: "Preto", price: 79.9, photoURL: "https://example.com/moto/pedaleira.jpg" },
  { name: "Banco de Moto", brand: "Selle", model: "B-606", year: "2024", color: "Preto", price: 249.9, photoURL: "https://example.com/moto/banco.jpg" },
  { name: "Carenagem Lateral", brand: "Paramotos", model: "C-707", year: "2024", color: "Azul", price: 199.9, photoURL: "https://example.com/moto/carenagem.jpg" },
  { name: "Escapamento", brand: "Pro Tork", model: "E-808", year: "2024", color: "Cromado", price: 399.9, photoURL: "https://example.com/moto/escapamento.jpg" },
  { name: "Protetor de Motor", brand: "Chapam", model: "P-909", year: "2024", color: "Preto", price: 179.9, photoURL: "https://example.com/moto/protetor_motor.jpg" },
  { name: "Bagageiro", brand: "Chapam", model: "B-101", year: "2024", color: "Preto", price: 149.9, photoURL: "https://example.com/moto/bagageiro.jpg" },
  { name: "Suporte de Placa", brand: "Pro Tork", model: "S-202", year: "2024", color: "Preto", price: 49.9, photoURL: "https://example.com/moto/suporte_placa.jpg" },
  { name: "Painel Digital", brand: "Magnetron", model: "P-303", year: "2024", color: "Nao se aplica", price: 299.9, photoURL: "https://example.com/moto/painel.jpg" },
  { name: "Sensor de Velocidade", brand: "Bosch", model: "S-404", year: "2024", color: "Nao se aplica", price: 119.9, photoURL: "https://example.com/moto/sensor_velocidade.jpg" },
  { name: "Chave de Ignição", brand: "Magnetron", model: "C-505", year: "2024", color: "Nao se aplica", price: 99.9, photoURL: "https://example.com/moto/chave_ignicao.jpg" },
  { name: "Trava de Guidão", brand: "Magnetron", model: "T-606", year: "2024", color: "Nao se aplica", price: 69.9, photoURL: "https://example.com/moto/trava_guidao.jpg" },
  { name: "Pneu Dianteiro", brand: "Pirelli", model: "P-707", year: "2024", color: "Nao se aplica", price: 289.9, photoURL: "https://example.com/moto/pneu_dianteiro.jpg" },
  { name: "Pneu Traseiro", brand: "Pirelli", model: "P-808", year: "2024", color: "Nao se aplica", price: 349.9, photoURL: "https://example.com/moto/pneu_traseiro.jpg" }
];
