export const FULL_SERVICE_CATALOG = [
  // Motor
  { name: 'Limpeza de TBI', category: 'Motor', vehicleType: 'carro', laborPrice: 150, partPrice: 20, description: 'Limpeza do corpo de borboleta' },
  { name: 'Troca de sensor MAP', category: 'Motor', vehicleType: 'carro', laborPrice: 100, partPrice: 150, description: '' },
  { name: 'Troca de sensor MAF', category: 'Motor', vehicleType: 'carro', laborPrice: 100, partPrice: 300, description: '' },
  { name: 'Troca de sensor de rotação', category: 'Motor', vehicleType: 'carro', laborPrice: 150, partPrice: 200, description: '' },
  { name: 'Troca de sensor de fase', category: 'Motor', vehicleType: 'carro', laborPrice: 150, partPrice: 180, description: '' },
  { name: 'Troca de sensor de temperatura', category: 'Motor', vehicleType: 'carro', laborPrice: 80, partPrice: 60, description: '' },
  { name: 'Troca de válvula PCV', category: 'Motor', vehicleType: 'carro', laborPrice: 80, partPrice: 90, description: '' },
  { name: 'Troca de válvula EGR', category: 'Motor', vehicleType: 'carro', laborPrice: 200, partPrice: 400, description: '' },
  { name: 'Troca de cárter', category: 'Motor', vehicleType: 'carro', laborPrice: 300, partPrice: 500, description: '' },
  { name: 'Troca de junta do cárter', category: 'Motor', vehicleType: 'carro', laborPrice: 250, partPrice: 80, description: '' },
  { name: 'Troca de polia do virabrequim', category: 'Motor', vehicleType: 'carro', laborPrice: 250, partPrice: 350, description: '' },
  { name: 'Troca de tucho hidráulico', category: 'Motor', vehicleType: 'carro', laborPrice: 500, partPrice: 600, description: '' },
  { name: 'Troca de balancim', category: 'Motor', vehicleType: 'carro', laborPrice: 400, partPrice: 300, description: '' },
  { name: 'Troca de árvore de comando', category: 'Motor', vehicleType: 'carro', laborPrice: 800, partPrice: 1200, description: '' },
  { name: 'Descarbonização de motor', category: 'Motor', vehicleType: 'carro', laborPrice: 400, partPrice: 100, description: '' },
  { name: 'Limpeza de sistema de admissão', category: 'Motor', vehicleType: 'carro', laborPrice: 200, partPrice: 50, description: '' },
  { name: 'Troca de coletor de admissão', category: 'Motor', vehicleType: 'carro', laborPrice: 300, partPrice: 800, description: '' },
  { name: 'Troca de coletor de escape', category: 'Motor', vehicleType: 'carro', laborPrice: 300, partPrice: 600, description: '' },
  { name: 'Troca de turbina (turbo)', category: 'Motor', vehicleType: 'carro', laborPrice: 600, partPrice: 2500, description: '' },
  { name: 'Reparo de turbo', category: 'Motor', vehicleType: 'carro', laborPrice: 800, partPrice: 500, description: '' },
  { name: 'Troca de intercooler', category: 'Motor', vehicleType: 'carro', laborPrice: 300, partPrice: 1000, description: '' },
  { name: 'Troca de mangueiras do turbo', category: 'Motor', vehicleType: 'carro', laborPrice: 150, partPrice: 300, description: '' },
  
  // Combustível
  { name: 'Troca de bomba de combustível', category: 'Combustível', vehicleType: 'carro', laborPrice: 200, partPrice: 400, description: '' },
  { name: 'Troca de pré-filtro', category: 'Combustível', vehicleType: 'carro', laborPrice: 100, partPrice: 50, description: '' },
  { name: 'Troca de regulador de pressão', category: 'Combustível', vehicleType: 'carro', laborPrice: 150, partPrice: 200, description: '' },
  { name: 'Limpeza de tanque de combustível', category: 'Combustível', vehicleType: 'carro', laborPrice: 300, partPrice: 0, description: '' },
  { name: 'Troca de tanque de combustível', category: 'Combustível', vehicleType: 'carro', laborPrice: 400, partPrice: 800, description: '' },
  { name: 'Limpeza completa do sistema de combustível', category: 'Combustível', vehicleType: 'carro', laborPrice: 250, partPrice: 100, description: '' },
  { name: 'Teste de pressão da bomba', category: 'Combustível', vehicleType: 'carro', laborPrice: 80, partPrice: 0, description: '' },
  { name: 'Troca de mangueiras de combustível', category: 'Combustível', vehicleType: 'carro', laborPrice: 150, partPrice: 100, description: '' },

  // Escape
  { name: 'Troca de escapamento', category: 'Escape', vehicleType: 'carro', laborPrice: 150, partPrice: 500, description: '' },
  { name: 'Troca de catalisador', category: 'Escape', vehicleType: 'carro', laborPrice: 200, partPrice: 800, description: '' },
  { name: 'Troca de silencioso', category: 'Escape', vehicleType: 'carro', laborPrice: 100, partPrice: 300, description: '' },
  { name: 'Troca de flexível do escapamento', category: 'Escape', vehicleType: 'carro', laborPrice: 150, partPrice: 150, description: '' },
  { name: 'Solda de escapamento', category: 'Escape', vehicleType: 'carro', laborPrice: 100, partPrice: 0, description: '' },
  { name: 'Substituição de suportes de escapamento', category: 'Escape', vehicleType: 'carro', laborPrice: 50, partPrice: 30, description: '' },

  // Freios
  { name: 'Troca de servo freio', category: 'Freios', vehicleType: 'carro', laborPrice: 250, partPrice: 600, description: '' },
  { name: 'Troca de sensor ABS', category: 'Freios', vehicleType: 'carro', laborPrice: 150, partPrice: 250, description: '' },
  { name: 'Troca de módulo ABS', category: 'Freios', vehicleType: 'carro', laborPrice: 400, partPrice: 1500, description: '' },
  { name: 'Troca de mangueira de freio', category: 'Freios', vehicleType: 'carro', laborPrice: 100, partPrice: 80, description: '' },
  { name: 'Troca de válvula equalizadora', category: 'Freios', vehicleType: 'carro', laborPrice: 150, partPrice: 200, description: '' },
  { name: 'Retífica de disco de freio', category: 'Freios', vehicleType: 'carro', laborPrice: 150, partPrice: 0, description: '' },
  { name: 'Limpeza do sistema de freio', category: 'Freios', vehicleType: 'carro', laborPrice: 100, partPrice: 20, description: '' },

  // Moto
  { name: 'Troca de corrente de comando', category: 'Motor', vehicleType: 'moto', laborPrice: 200, partPrice: 150, description: '' },
  { name: 'Troca de comando de válvulas', category: 'Motor', vehicleType: 'moto', laborPrice: 300, partPrice: 400, description: '' },
  { name: 'Troca de virabrequim', category: 'Motor', vehicleType: 'moto', laborPrice: 600, partPrice: 800, description: '' },
  { name: 'Troca de embreagem da moto', category: 'Motor', vehicleType: 'moto', laborPrice: 200, partPrice: 300, description: '' },
  { name: 'Troca de discos de embreagem', category: 'Motor', vehicleType: 'moto', laborPrice: 150, partPrice: 200, description: '' },
  { name: 'Troca de mola de embreagem', category: 'Motor', vehicleType: 'moto', laborPrice: 100, partPrice: 50, description: '' },
  { name: 'Troca de tampa do motor', category: 'Motor', vehicleType: 'moto', laborPrice: 150, partPrice: 250, description: '' },
  { name: 'Troca de junta do cabeçote', category: 'Motor', vehicleType: 'moto', laborPrice: 250, partPrice: 100, description: '' },
  { name: 'Troca de junta da tampa do motor', category: 'Motor', vehicleType: 'moto', laborPrice: 100, partPrice: 50, description: '' },
  { name: 'Limpeza interna do motor', category: 'Motor', vehicleType: 'moto', laborPrice: 200, partPrice: 50, description: '' },

  // Premium
  { name: 'Remapeamento de ECU', category: 'Premium', vehicleType: 'carro', laborPrice: 1000, partPrice: 0, description: '' },
  { name: 'Chip de potência', category: 'Premium', vehicleType: 'carro', laborPrice: 300, partPrice: 500, description: '' },
  { name: 'Diagnóstico avançado de sensores', category: 'Premium', vehicleType: 'carro', laborPrice: 300, partPrice: 0, description: '' },
  { name: 'Telemetria automotiva', category: 'Premium', vehicleType: 'carro', laborPrice: 500, partPrice: 200, description: '' },
  { name: 'Remap de injeção', category: 'Premium', vehicleType: 'moto', laborPrice: 600, partPrice: 0, description: '' },
  { name: 'Preparação de motor', category: 'Premium', vehicleType: 'moto', laborPrice: 1500, partPrice: 1000, description: '' },
  { name: 'Ajuste de suspensão esportiva', category: 'Premium', vehicleType: 'moto', laborPrice: 400, partPrice: 200, description: '' },

  // Lava-Jato
  { name: 'Lavagem Simples', category: 'Lavagem Básica', vehicleType: 'lava_jato', laborPrice: 30, partPrice: 0, description: 'Lavagem externa com shampoo' },
  { name: 'Lavagem Completa', category: 'Lavagem Básica', vehicleType: 'lava_jato', laborPrice: 50, partPrice: 0, description: 'Lavagem externa + aspiração' },
  { name: 'Lavagem com Cera', category: 'Lavagem Básica', vehicleType: 'lava_jato', laborPrice: 70, partPrice: 0, description: 'Aplicação de cera líquida' },
  { name: 'Lavagem de Moto', category: 'Lavagem Básica', vehicleType: 'lava_jato', laborPrice: 20, partPrice: 0, description: 'Lavagem completa de moto' },
  { name: 'Lavagem Ecológica', category: 'Lavagem Básica', vehicleType: 'lava_jato', laborPrice: 60, partPrice: 0, description: 'Lavagem com baixo consumo' },
  { name: 'Aspiração Interna', category: 'Limpeza Interna', vehicleType: 'lava_jato', laborPrice: 25, partPrice: 0, description: 'Aspiração de bancos e carpetes' },
  { name: 'Limpeza de Bancos', category: 'Limpeza Interna', vehicleType: 'lava_jato', laborPrice: 40, partPrice: 0, description: 'Limpeza de bancos em tecido' },
  { name: 'Higienização Interna', category: 'Limpeza Interna', vehicleType: 'lava_jato', laborPrice: 80, partPrice: 0, description: 'Eliminação de odores' },
  { name: 'Limpeza de Painel', category: 'Limpeza Interna', vehicleType: 'lava_jato', laborPrice: 20, partPrice: 0, description: 'Revitalização do painel' },
  { name: 'Higienização Interna Moto', category: 'Limpeza Interna', vehicleType: 'lava_jato', laborPrice: 15, partPrice: 0, description: 'Higienização interna especializada' },
  { name: 'Polimento Técnico', category: 'Estética Automotiva', vehicleType: 'lava_jato', laborPrice: 200, partPrice: 0, description: 'Remoção de riscos leves' },
  { name: 'Cristalização', category: 'Estética Automotiva', vehicleType: 'lava_jato', laborPrice: 250, partPrice: 0, description: 'Proteção e brilho' },
  { name: 'Vitrificação', category: 'Estética Automotiva', vehicleType: 'lava_jato', laborPrice: 600, partPrice: 0, description: 'Proteção cerâmica' },
  { name: 'Enceramento', category: 'Estética Automotiva', vehicleType: 'lava_jato', laborPrice: 100, partPrice: 0, description: 'Aplicação de cera' },
  { name: 'Detalhamento Motor', category: 'Detalhamento', vehicleType: 'lava_jato', laborPrice: 300, partPrice: 0, description: 'Limpeza interna e externa' },
  { name: 'Limpeza de Chassis', category: 'Detalhamento', vehicleType: 'lava_jato', laborPrice: 120, partPrice: 0, description: 'Limpeza técnica de chassis' },
  { name: 'Limpeza Caixa Roda', category: 'Detalhamento', vehicleType: 'lava_jato', laborPrice: 50, partPrice: 0, description: 'Remoção de sujeira pesada' },
  { name: 'Cristalização Vidros', category: 'Vidros', vehicleType: 'lava_jato', laborPrice: 80, partPrice: 0, description: 'Repelente de água' },
  { name: 'Limpeza de Vidros', category: 'Vidros', vehicleType: 'lava_jato', laborPrice: 30, partPrice: 0, description: 'Limpeza completa' },
  { name: 'Limpeza de Rodas', category: 'Rodas e Pneus', vehicleType: 'lava_jato', laborPrice: 40, partPrice: 0, description: 'Limpeza profunda' },
  { name: 'Pretinho', category: 'Rodas e Pneus', vehicleType: 'lava_jato', laborPrice: 20, partPrice: 0, description: 'Revitalização de pneus' },
  { name: 'Revitalização Plásticos', category: 'Rodas e Pneus', vehicleType: 'lava_jato', laborPrice: 15, partPrice: 0, description: 'Produto para plásticos e borrachas' },
  { name: 'Higienização Ozônio', category: 'Premium', vehicleType: 'lava_jato', laborPrice: 350, partPrice: 0, description: 'Limpeza profunda premium' },
  { name: 'Proteção Cerâmica Rodas', category: 'Premium', vehicleType: 'lava_jato', laborPrice: 800, partPrice: 0, description: 'Proteção duradoura' },

  // Som Automotivo
  { name: 'Instalação de Som Básico', category: 'Instalação', vehicleType: 'som_automotivo', laborPrice: 120, partPrice: 0, description: 'Instalação de rádio e alto-falantes simples' },
  { name: 'Instalação de Multimídia', category: 'Instalação', vehicleType: 'som_automotivo', laborPrice: 250, partPrice: 0, description: 'Instalação de central multimídia com câmera' },
  { name: 'Instalação de Alto-falantes', category: 'Instalação', vehicleType: 'som_automotivo', laborPrice: 100, partPrice: 0, description: 'Instalação ou substituição de falantes' },
  { name: 'Instalação de Subwoofer', category: 'Instalação', vehicleType: 'som_automotivo', laborPrice: 150, partPrice: 0, description: 'Instalação de subwoofer com regulagem' },
  { name: 'Instalação de Módulo Amplificador', category: 'Instalação', vehicleType: 'som_automotivo', laborPrice: 200, partPrice: 0, description: 'Instalação de amplificador com cabeamento' },
  { name: 'Instalação de Som em Moto', category: 'Instalação', vehicleType: 'som_automotivo', laborPrice: 180, partPrice: 0, description: 'Instalação de kit de som para motocicleta' },
  { name: 'Upgrade de Som Completo', category: 'Upgrade', vehicleType: 'som_automotivo', laborPrice: 500, partPrice: 0, description: 'Atualização total do sistema de som' },
  { name: 'Projeto de Som Personalizado', category: 'Upgrade', vehicleType: 'som_automotivo', laborPrice: 800, partPrice: 0, description: 'Planejamento completo com foco em qualidade' },
  { name: 'Montagem de Som Paredão', category: 'Upgrade', vehicleType: 'som_automotivo', laborPrice: 1500, partPrice: 0, description: 'Montagem de som de alta potência' },
  { name: 'Montagem de Som Trio', category: 'Upgrade', vehicleType: 'som_automotivo', laborPrice: 1200, partPrice: 0, description: 'Sistema voltado para som externo' },
  { name: 'Instalação de Cabo RCA', category: 'Cabeamento', vehicleType: 'som_automotivo', laborPrice: 80, partPrice: 0, description: 'Passagem e instalação de cabos RCA' },
  { name: 'Instalação de Cabo de Força', category: 'Cabeamento', vehicleType: 'som_automotivo', laborPrice: 90, partPrice: 0, description: 'Instalação de alimentação para módulo' },
  { name: 'Organização de Fiação', category: 'Cabeamento', vehicleType: 'som_automotivo', laborPrice: 70, partPrice: 0, description: 'Organização e proteção do sistema elétrico' },
  { name: 'Reparo de Cabeamento', category: 'Cabeamento', vehicleType: 'som_automotivo', laborPrice: 100, partPrice: 0, description: 'Correção de falhas elétricas no som' },
  { name: 'Diagnóstico de Som', category: 'Diagnóstico', vehicleType: 'som_automotivo', laborPrice: 60, partPrice: 0, description: 'Verificação de falhas no sistema de áudio' },
  { name: 'Teste de Amplificador', category: 'Diagnóstico', vehicleType: 'som_automotivo', laborPrice: 50, partPrice: 0, description: 'Avaliação de funcionamento do módulo' },
  { name: 'Teste de Alto-falantes', category: 'Diagnóstico', vehicleType: 'som_automotivo', laborPrice: 40, partPrice: 0, description: 'Teste individual dos falantes' },
  { name: 'Identificação de Ruído', category: 'Diagnóstico', vehicleType: 'som_automotivo', laborPrice: 70, partPrice: 0, description: 'Detecção de interferências' },
  { name: 'Reparo de Módulo', category: 'Manutenção', vehicleType: 'som_automotivo', laborPrice: 150, partPrice: 0, description: 'Reparo de amplificadores' },
  { name: 'Reparo de Alto-falante', category: 'Manutenção', vehicleType: 'som_automotivo', laborPrice: 100, partPrice: 0, description: 'Recuperação de falantes' },
  { name: 'Troca de Conectores', category: 'Manutenção', vehicleType: 'som_automotivo', laborPrice: 50, partPrice: 0, description: 'Substituição de conectores danificados' },
  { name: 'Limpeza de Sistema de Som', category: 'Manutenção', vehicleType: 'som_automotivo', laborPrice: 60, partPrice: 0, description: 'Limpeza geral dos componentes' },
  { name: 'Instalação de LED Interno', category: 'Personalização', vehicleType: 'som_automotivo', laborPrice: 120, partPrice: 0, description: 'Iluminação decorativa interna' },
  { name: 'Iluminação para Som', category: 'Personalização', vehicleType: 'som_automotivo', laborPrice: 150, partPrice: 0, description: 'LED sincronizado com som' },
  { name: 'Painel Personalizado', category: 'Personalização', vehicleType: 'som_automotivo', laborPrice: 300, partPrice: 0, description: 'Customização estética do painel' },

  // Auto Elétrica
  { name: 'Diagnóstico Elétrico', category: 'Sistema Elétrico', vehicleType: 'auto_eletrica', laborPrice: 80, partPrice: 0, description: 'Identificação de falhas elétricas' },
  { name: 'Reparo de Chicote', category: 'Sistema Elétrico', vehicleType: 'auto_eletrica', laborPrice: 120, partPrice: 0, description: 'Correção de fiação danificada' },
  { name: 'Troca de Fusíveis', category: 'Sistema Elétrico', vehicleType: 'auto_eletrica', laborPrice: 30, partPrice: 0, description: 'Substituição de fusíveis queimados' },
  { name: 'Reparo de Curto-Circuito', category: 'Sistema Elétrico', vehicleType: 'auto_eletrica', laborPrice: 150, partPrice: 0, description: 'Identificação e correção de curto' },
  { name: 'Revisão Elétrica Geral', category: 'Sistema Elétrico', vehicleType: 'auto_eletrica', laborPrice: 200, partPrice: 0, description: 'Verificação completa do sistema' },
  { name: 'Troca de Bateria', category: 'Bateria', vehicleType: 'auto_eletrica', laborPrice: 50, partPrice: 0, description: 'Instalação de bateria nova' },
  { name: 'Teste de Bateria', category: 'Bateria', vehicleType: 'auto_eletrica', laborPrice: 30, partPrice: 0, description: 'Avaliação de carga e vida útil' },
  { name: 'Carga de Bateria', category: 'Bateria', vehicleType: 'auto_eletrica', laborPrice: 40, partPrice: 0, description: 'Recarga de bateria descarregada' },
  { name: 'Instalação de Bateria Auxiliar', category: 'Bateria', vehicleType: 'auto_eletrica', laborPrice: 120, partPrice: 0, description: 'Instalação para sistemas adicionais' },
  { name: 'Troca de Alternador', category: 'Sistema de Carga', vehicleType: 'auto_eletrica', laborPrice: 250, partPrice: 0, description: 'Substituição do alternador' },
  { name: 'Reparo de Alternador', category: 'Sistema de Carga', vehicleType: 'auto_eletrica', laborPrice: 200, partPrice: 0, description: 'Manutenção do alternador' },
  { name: 'Teste de Alternador', category: 'Sistema de Carga', vehicleType: 'auto_eletrica', laborPrice: 60, partPrice: 0, description: 'Avaliação de funcionamento' },
  { name: 'Troca de Motor de Arranque', category: 'Partida', vehicleType: 'auto_eletrica', laborPrice: 220, partPrice: 0, description: 'Substituição do motor de partida' },
  { name: 'Reparo de Motor de Arranque', category: 'Partida', vehicleType: 'auto_eletrica', laborPrice: 180, partPrice: 0, description: 'Manutenção do sistema de partida' },
  { name: 'Troca de Faróis', category: 'Iluminação', vehicleType: 'auto_eletrica', laborPrice: 80, partPrice: 0, description: 'Substituição de faróis' },
  { name: 'Troca de Lâmpadas', category: 'Iluminação', vehicleType: 'auto_eletrica', laborPrice: 40, partPrice: 0, description: 'Troca de lâmpadas queimadas' },
  { name: 'Instalação de LED', category: 'Iluminação', vehicleType: 'auto_eletrica', laborPrice: 100, partPrice: 0, description: 'Instalação de lâmpadas LED' },
  { name: 'Instalação de Xenon', category: 'Iluminação', vehicleType: 'auto_eletrica', laborPrice: 150, partPrice: 0, description: 'Instalação de kit xenon' },
  { name: 'Reparo de Iluminação', category: 'Iluminação', vehicleType: 'auto_eletrica', laborPrice: 90, partPrice: 0, description: 'Correção de falhas de luz' },
  { name: 'Instalação de Alarme', category: 'Acessórios', vehicleType: 'auto_eletrica', laborPrice: 180, partPrice: 0, description: 'Instalação de sistema de segurança' },
  { name: 'Instalação de Trava Elétrica', category: 'Acessórios', vehicleType: 'auto_eletrica', laborPrice: 150, partPrice: 0, description: 'Automatização de travas' },
  { name: 'Instalação de Vidro Elétrico', category: 'Acessórios', vehicleType: 'auto_eletrica', laborPrice: 200, partPrice: 0, description: 'Conversão manual para elétrico' },
  { name: 'Instalação de Sensor de Ré', category: 'Acessórios', vehicleType: 'auto_eletrica', laborPrice: 120, partPrice: 0, description: 'Sensor de estacionamento' },
  { name: 'Instalação de Câmera de Ré', category: 'Acessórios', vehicleType: 'auto_eletrica', laborPrice: 180, partPrice: 0, description: 'Instalação com multimídia' },
  { name: 'Instalação de Rastreador', category: 'Acessórios', vehicleType: 'auto_eletrica', laborPrice: 200, partPrice: 0, description: 'Sistema de rastreamento veicular' },
  { name: 'Diagnóstico Eletrônico', category: 'Eletrônica', vehicleType: 'auto_eletrica', laborPrice: 100, partPrice: 0, description: 'Scanner completo' },
  { name: 'Scanner Automotivo', category: 'Eletrônica', vehicleType: 'auto_eletrica', laborPrice: 80, partPrice: 0, description: 'Leitura de códigos de erro' },
  { name: 'Reset de Módulo', category: 'Eletrônica', vehicleType: 'auto_eletrica', laborPrice: 70, partPrice: 0, description: 'Limpeza de falhas do sistema' },
  { name: 'Programação de ECU', category: 'Eletrônica', vehicleType: 'auto_eletrica', laborPrice: 300, partPrice: 0, description: 'Reconfiguração eletrônica do veículo' },
];
